name: Documentation request
description: 추가할 guide나 example을 제안해주세요.
title: "[Guide] "
labels: [documentation, enhancement]
body:
  - type: textarea
    id: use_case
    attributes:
      label: 필요한 사용 사례
    validations:
      required: true
  - type: textarea
    id: outline
    attributes:
      label: 포함하면 좋은 내용
